---
title: Verken een 3D-wereld
hero_image: images/banner.png
description:
  - Maak een 3D-wereld in Unity en verken deze met een geanimeerd 
  - 3D-persoon
meta_title: Learn Unity | Game development | 3D world
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Create a 3D world in Unity and explore it with an animated 3D player character.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Stel de 3D-scène in
  - 
    title: Voeg een Speler toe
    completion:
      - engaged
  - 
    title: Voeg een beweging toe
  - 
    title: Animatie en camerapositie
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
