---
title: Explore a 3D world
hero_image: images/banner.png
description:
  Create a 3D world in Unity and explore it with an animated 3D player
  character
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: You will make
  - title: Set the 3D scene
  - title: Add a Player character
    completion:
      - engaged
  - title: Add character movement
  - title: Animation and camera position
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
