---
title: اكتشف العالم الثلاثي الأبعاد
hero_image: images/banner.png
description:
  - Create a 3D world in Unity and explore it with an animated 3D player
  - character
meta_title: Learn Unity | Game development | 3D world
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Create a 3D world in Unity and explore it with an animated 3D player character.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: اضبط المشهد ثلاثي الأبعاد
  - 
    title: أضف شخصية ألاعب
    completion:
      - engaged
  - 
    title: أضف الحركة الشخصية
  - 
    title: الرسوم المتحركة وموضع الكاميرا
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: قم بتطوير مشروعك
  - 
    title: ما هي الخطوة التالية؟
